// AUTO-GENERATED — do not edit by hand

export const ENDPOINTS = {
  deleteApiFilesById: { method: 'DELETE', path: '/api/files/:id', exposesBy: 'File Explorer', errors: [] },
  deleteApiFoldersById: { method: 'DELETE', path: '/api/folders/:id', exposesBy: 'File Explorer', errors: [] },
  deleteApiMessagesById: { method: 'DELETE', path: '/api/messages/:id', exposesBy: 'General Channels', errors: [] },
  deleteApiQuestionsByIdResolve: { method: 'DELETE', path: '/api/questions/:id/resolve', exposesBy: 'Active Question Chats', errors: [] },
  deleteApiReferencesById: { method: 'DELETE', path: '/api/references/:id', exposesBy: 'Message Reference and Annotation', errors: [] },
  getApiChannelsByIdMessages: { method: 'GET', path: '/api/channels/:id/messages', exposesBy: 'General Channels', errors: [] },
  getApiFileVersionsByIdPagesByPage: { method: 'GET', path: '/api/file-versions/:id/pages/:page', exposesBy: 'Message Reference and Annotation', errors: [] },
  getApiFilesByIdDownload: { method: 'GET', path: '/api/files/:id/download', exposesBy: 'File Explorer', errors: [] },
  getApiFilesByIdVersions: { method: 'GET', path: '/api/files/:id/versions', exposesBy: 'File Explorer', errors: [] },
  getApiProjects: { method: 'GET', path: '/api/projects', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  getApiProjectsById: { method: 'GET', path: '/api/projects/:id', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  getApiProjectsByIdChannels: { method: 'GET', path: '/api/projects/:id/channels', exposesBy: 'General Channels', errors: [] },
  getApiProjectsByIdFiles: { method: 'GET', path: '/api/projects/:id/files', exposesBy: 'File Explorer', errors: [] },
  getApiProjectsByIdQuestions: { method: 'GET', path: '/api/projects/:id/questions', exposesBy: 'Active Question Chats', errors: [] },
  getApiProjectsByIdUnread: { method: 'GET', path: '/api/projects/:id/unread', exposesBy: 'Unread Message Indicators', errors: [] },
  getApiRealtimeSocket: { method: 'GET', path: '/api/realtime/socket', exposesBy: 'General Channels', errors: [] },
  getApiReferencesById: { method: 'GET', path: '/api/references/:id', exposesBy: 'Message Reference and Annotation', errors: [] },
  getApiUsers: { method: 'GET', path: '/api/users', exposesBy: 'Authentication and Roles', errors: [] },
  patchApiFilesById: { method: 'PATCH', path: '/api/files/:id', exposesBy: 'File Explorer', errors: [] },
  patchApiFoldersById: { method: 'PATCH', path: '/api/folders/:id', exposesBy: 'File Explorer', errors: [] },
  patchApiMessagesById: { method: 'PATCH', path: '/api/messages/:id', exposesBy: 'General Channels', errors: [] },
  patchApiProjectsById: { method: 'PATCH', path: '/api/projects/:id', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  patchApiUsersById: { method: 'PATCH', path: '/api/users/:id', exposesBy: 'Authentication and Roles', errors: [] },
  postApiAuthLogin: { method: 'POST', path: '/api/auth/login', exposesBy: 'Authentication and Roles', errors: [] },
  postApiAuthLogout: { method: 'POST', path: '/api/auth/logout', exposesBy: 'Authentication and Roles', errors: [] },
  postApiChannelsByIdMessages: { method: 'POST', path: '/api/channels/:id/messages', exposesBy: 'General Channels', errors: [] },
  postApiChannelsByIdRead: { method: 'POST', path: '/api/channels/:id/read', exposesBy: 'Unread Message Indicators', errors: [] },
  postApiInvitationsByIdResend: { method: 'POST', path: '/api/invitations/:id/resend', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  postApiInvitationsAccept: { method: 'POST', path: '/api/invitations/accept', exposesBy: 'Authentication and Roles', errors: [] },
  postApiMessagesByIdReference: { method: 'POST', path: '/api/messages/:id/reference', exposesBy: 'Message Reference and Annotation', errors: [] },
  postApiProjects: { method: 'POST', path: '/api/projects', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  postApiProjectsByIdArchive: { method: 'POST', path: '/api/projects/:id/archive', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  postApiProjectsByIdChannels: { method: 'POST', path: '/api/projects/:id/channels', exposesBy: 'General Channels', errors: [] },
  postApiProjectsByIdFiles: { method: 'POST', path: '/api/projects/:id/files', exposesBy: 'File Explorer', errors: [] },
  postApiProjectsByIdFolders: { method: 'POST', path: '/api/projects/:id/folders', exposesBy: 'File Explorer', errors: [] },
  postApiProjectsByIdInvitations: { method: 'POST', path: '/api/projects/:id/invitations', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  postApiProjectsByIdMembers: { method: 'POST', path: '/api/projects/:id/members', exposesBy: 'Projects and External Organization Spaces', errors: [] },
  postApiProjectsByIdQuestions: { method: 'POST', path: '/api/projects/:id/questions', exposesBy: 'Active Question Chats', errors: [] },
  postApiQuestionsByIdResolve: { method: 'POST', path: '/api/questions/:id/resolve', exposesBy: 'Active Question Chats', errors: [] },
  postApiUsers: { method: 'POST', path: '/api/users', exposesBy: 'Authentication and Roles', errors: [] },
  putApiReferencesById: { method: 'PUT', path: '/api/references/:id', exposesBy: 'Message Reference and Annotation', errors: [] }
} as const;
